# Generated by Django 2.0 on 2020-03-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('alt_phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=7)),
                ('home_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15, unique=True)),
                ('manufacturer_name', models.CharField(max_length=25)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'TWO_WHEELER'), ('FOUR_WHEELER', 'FOUR_WHEELER')], max_length=15)),
                ('model_name', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Register')),
            ],
        ),
    ]
