# Generated by Django 2.0 on 2020-03-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15, unique=True)),
                ('vehicle_type', models.CharField(default='BIKE', max_length=15)),
                ('model_name', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.BikeManufacturer')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Register')),
            ],
        ),
        migrations.CreateModel(
            name='CarVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15, unique=True)),
                ('vehicle_type', models.CharField(default='CAR', max_length=15)),
                ('model_name', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.CarManufacturer')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Register')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owned_by',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
