# Generated by Django 2.0 on 2020-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200311_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='vehicle_delivery_address',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='home_address',
            field=models.CharField(max_length=1024),
        ),
    ]
