# Generated by Django 2.0 on 2020-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200424_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior'), ('Indore', 'Indore'), ('Chhatarpur', 'Chhatarpur'), ('Other', 'Other')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
