# Generated by Django 2.2 on 2020-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200613_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikevehicle',
            name='owned_by',
            field=models.EmailField(max_length=254),
        ),
    ]
