# Generated by Django 2.0 on 2020-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemanufacturer',
            name='manufacturer_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='carmanufacturer',
            name='manufacturer_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
