# Generated by Django 2.0 on 2020-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20200311_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemanufacturer',
            name='bikebrands',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='carmanufacturer',
            name='carbrand',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
