# Generated by Django 2.2 on 2020-05-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20200421_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemanufacturer',
            name='bikebrands',
        ),
        migrations.RemoveField(
            model_name='carmanufacturer',
            name='carbrand',
        ),
    ]
