# Generated by Django 2.0 on 2020-03-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0002_auto_20200311_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=20)),
                ('opening_time', models.CharField(max_length=20)),
                ('closing_time', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.BikeManufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CarServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_time', models.CharField(max_length=20)),
                ('closing_time', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.CarManufacturer')),
            ],
        ),
    ]
