# Generated by Django 2.2 on 2020-06-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=40)),
                ('bookdate', models.DateField()),
                ('bookedfor', models.CharField(choices=[('REPAIR', 'REPAIR'), ('SERVICE', 'SERVICE'), ('REPAIR AND SERVICE', 'REPAIR AND SERVICE')], max_length=40)),
                ('estimatedcost', models.IntegerField(blank=True, null=True)),
                ('actualcost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('servicestatus', models.CharField(choices=[('REQUEST BOOKING', 'REQUESTBOOKING'), ('CANCELLED BY OWNER', 'CANCELLED BY OWNER'), ('CANCELLED BY ADMIN', 'CANCELLED BY ADMIN'), ('CONFIRM BY ADMIN', 'CONFIRM BY ADMIN'), ('PICKED UP', 'PICKED UP'), ('PICKED UP', 'PICKED UP'), ('SERVICE STARTED', 'SERVICE STARTED'), ('SERVICE COMPLETED', 'SERVICE COMPLETED'), ('PAYMENT DONE', 'PAYMENT DONE'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='REQUEST BOOKING', max_length=30)),
                ('carservicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecenter.CarServiceCenter')),
            ],
        ),
        migrations.CreateModel(
            name='BikeServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=40)),
                ('bookdate', models.DateField()),
                ('bookedfor', models.CharField(choices=[('REPAIR', 'REPAIR'), ('SERVICE', 'SERVICE'), ('REPAIR AND SERVICE', 'REPAIR AND SERVICE')], max_length=40)),
                ('estimatedcost', models.IntegerField(blank=True, null=True)),
                ('actualcost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('servicestatus', models.CharField(choices=[('REQUEST BOOKING', 'REQUESTBOOKING'), ('CANCELLED BY OWNER', 'CANCELLED BY OWNER'), ('CANCELLED BY ADMIN', 'CANCELLED BY ADMIN'), ('CONFIRM BY ADMIN', 'CONFIRM BY ADMIN'), ('PICKED UP', 'PICKED UP'), ('PICKED UP', 'PICKED UP'), ('SERVICE STARTED', 'SERVICE STARTED'), ('SERVICE COMPLETED', 'SERVICE COMPLETED'), ('PAYMENT DONE', 'PAYMENT DONE'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='REQUEST BOOKING', max_length=30)),
                ('bikservicecenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecenter.BikeServiceCenter')),
            ],
        ),
    ]
