# Generated by Django 2.2 on 2020-06-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0002_bikeservicerequest_carservicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeservicerequest',
            old_name='bikservicecenter',
            new_name='bikeservicecenter',
        ),
    ]
