# Generated by Django 2.2 on 2020-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecenter', '0003_auto_20200613_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeservicerequest',
            name='owned_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='owned_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
